### ISSUE TITLE
Loosen version bounds on base (allow 4.16) for ghc 9.2

### ISSUE THREAD

**Issue by avh4** [diagrams/diagrams-gtk#11]
I've confirmed the package compiles successfully with:
- ghc-9.2.5 / base-4.16.4.0
- ghc-9.2.7 / base-4.16.4.0

And I've confirmed it works correctly in an actual program with:
- ghc-9.2.5 / base-4.16.4.0

It'd probably be helpful to allow base-4.17 (ghc-9.4) too, though I don't have a working ghc 9.4 environment to test it with.

**Comment by byorgey** [comment]
Thanks for the nudge!  I'll see about updating this shortly.

We probably can't actually allow base-4.17 since I suspect the `cairo` package (which this package depends on via `diagrams-cairo`) won't build with it.

**Comment by byorgey** [comment]
Closed by ac2c0d10 .  Updated version 1.4 on Hackage to include this revision.
