### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by nomeata** [diagrams/diagrams-gtk#3]
Hi,

while other diagrams packages are part of stackage, this is not. Is there a specific reason?

Greetings,
Joachim

**Comment by byorgey** [comment]
No, just an oversight I think.

**Comment by nomeata** [comment]
Ok, then I’ll not remove it from Debian just yet (where I’m pushing for a policy of only having packages in Stackage, or select other “key” packages with their dependencies).

**Comment by byorgey** [comment]
We have a bit of upper bounds updating to do first, and once that's done I'll submit it for inclusion in stackage.

**Comment by byorgey** [comment]
See https://github.com/fpco/stackage/pull/1178 .
