### ISSUE TITLE
Failure to compile with GHC 8.6

### ISSUE THREAD

**Issue by ghost** [diagrams/diagrams-gtk#9]
This backend has an constraint on the version of base that prevents installation with base >= 4.12, distributed with GHC versions >= 8.6

**Comment by avh4** [comment]
FYI, this apparently was fixed in https://github.com/diagrams/diagrams-gtk/commit/7f1b6a38adfb2c11eaaf4af9c14364f0ca9edca9

(I made a new issue for ghc 9.2: https://github.com/diagrams/diagrams-gtk/issues/11)
